### ISSUE TITLE
text is covered by image

### ISSUE THREAD

**Issue by phinexdaz** [daohoangson/flutter_widget_from_html#114]
Hi, i found a issue when rendering texts and images,  thanks

https://gist.github.com/phinexdaz/c2c6b1ce710ff04c4fa26fdc5ef71a03

<img width="301" alt="截屏2019-11-0318 48 08" src="https://user-images.githubusercontent.com/4945098/68084124-62dbb600-fe6c-11e9-8a75-74e7d9f2ab30.png">

**Comment by daohoangson** [comment]
Thank you for the detailed report. I'll see what can be done.

Oh, which Flutter version are you using? Are you on stable channel? Output of `flutter doctor` would be useful too.

**Comment by phinexdaz** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.15.1 19B88, locale zh-Hans)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
[!] VS Code (version 1.38.0)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.

**Comment by daohoangson** [comment]
Thank you for your patience. I have been able to reproduce your report and tracked down this issue https://github.com/flutter/flutter/issues/39296. Basically it is the expected behavior due to some legacy reason. The Flutter dev said (in that link) that they plan to do it the right way but provide no time frame.

The suggested workaround is to render each block of text independently which means you need to break down your big DIV and put each image+caption into a P (paragraph). Something like this should work: https://gist.github.com/daohoangson/d570fca6e64a94ca99a67b9ad2aa4b3b

<img width="507" alt="Screen Shot 2019-11-04 at 10 34 43 AM" src="https://user-images.githubusercontent.com/239336/68098352-c3abd280-feee-11e9-9ed2-6eddf9a2bc55.png">

**Comment by phinexdaz** [comment]
In my APP, the HTML source is uneditable, i cannot put each image+caption into a paragraph, i will look for other solutions.
Thank you just the same.
