### ISSUE TITLE
Wrong list markers style

### ISSUE THREAD

**Issue by Edwin-tw** [daohoangson/flutter_widget_from_html#179]
Both list markers using CSS style type "list-style-type:circle" and "list-style-type:square" are displaying different markers than expected :
list-style-type:circle : "-" instead of "⚬"
list-style-type:square : "+" instead of "▪"

Could it be adjusted, please ?

**Comment by daohoangson** [comment]
This is intentional because the default font doesn't have suitable circle / square characters, they are either too small or too big. The ones you suggested is too big for example. It's possible to use custom font or icon for this but doing so will require additional assets so I used `-` and `+`.

If you want to change these to something else, you can use a custom `WidgetFactory` and override the method [getListStyleMarker](https://github.com/daohoangson/flutter_widget_from_html/blob/0507b7019eb06bc30323bc3feeff6933d40f5126/packages/core/lib/src/core_widget_factory.dart#L380).

**Comment by daohoangson** [comment]
Starting from v0.5.0 (commit c4cff9f6ce4dcc1789749fef5a54a32b889e8fa2 to be exact), the marker bullet has been updated. I'm closing this issue.
