### ISSUE TITLE
 Do not load Image in base64

### ISSUE THREAD

**Issue by ed5on** [daohoangson/flutter_widget_from_html#376]
I am using:

- Flutter 1.22.3

- flutter_widget_from_html 0.5.1 + 5

does not render content when adding a base 64 image generated by

- flutter_html_editor 1.0.0

Attached link of the html that is generated:
https://gist.githubusercontent.com/ed5on/5f372b9762dd1e13709e7f1b29ccb5e2/raw/b0d2b83b5bb7c27f3524238e0eed34faef7bb6a8/html.txt

**Comment by daohoangson** [comment]
Did you put together the data URI yourself or the editor package generated that complete HTML? I asked because the data URI has an extra space character making it an invalid base64 encoded string.

This:

```
image/png;base64, /9j/
```

Should be:

```
image/png;base64,/9j/
```

Remove the space and it will work, like this:

<img src="https://user-images.githubusercontent.com/239336/99691737-1c2f1d00-2abc-11eb-95b0-3b62929c6406.png" width="300" />

**Comment by ed5on** [comment]
Thanks for the prompt response.
It is the package that generates all the html code.
Checking the package code, I saw that concatenating base64 adds a space to your code.
The solutions is to modify that piece of code, it works.
