### ISSUE TITLE
[web] <a> tag don't work correctly with tag <br> after and text on next line

### ISSUE THREAD

**Issue by DmitryTryput** [daohoangson/flutter_widget_from_html#387]
Callback onTapUrl isn't called  if we have text on next line:
![image](https://user-images.githubusercontent.com/20545010/101023708-353bd180-3584-11eb-8a36-35cf01d62729.png)

But on bigger resolution, when text fit in one line, everything works correctly 
![image](https://user-images.githubusercontent.com/20545010/101023632-19383000-3584-11eb-9c5e-9c664277eaea.png)

And also works correctly if we use tag \<br> after \<a> tag:
![image](https://user-images.githubusercontent.com/20545010/101024630-6ec10c80-3585-11eb-8fda-550edfdf9b36.png)

**Comment by daohoangson** [comment]
Thank you for the detailed report. This is indeed a weird and serious bug. I'll try to fix it asap.

**Comment by jarlestabell** [comment]
I've stumbled into the same problem and as a temporary workaround I've added an extra space at the end of the link text.
(Because I auto generate these links and don't always know the context)

**Comment by daohoangson** [comment]
<img width="1312" alt="Screen Shot 2021-02-11 at 22 20 36" src="https://user-images.githubusercontent.com/239336/107657086-6557cd00-6cb7-11eb-829a-574f8d278485.png">

This is likely an issue within Flutter. I have just tried this with the latest beta and it seemed to work fine now. Since this issue is fairly old already, I'm closing it now. Feel free to reopen if it's still happening with you.
