### ISSUE TITLE
Remove padding image in figure tag

### ISSUE THREAD

**Issue by HenglyEver** [daohoangson/flutter_widget_from_html#401]
I use the image in the figure tag and I don't want the padding. Can you please tell me how to remove the padding? Thanks.

![133114840_215230683535070_5281828874820160535_n](https://user-images.githubusercontent.com/35974032/103104170-3da19c80-4658-11eb-80aa-ffbbdf553e9b.jpg)

**Comment by daohoangson** [comment]
The FIGURE has a default margin to match the way browsers render the tag. If you have control of the HTML, you can use inline style to remove it. Or you can use `customStylesBuilder` to remove margin for all FIGURE tags. Something like this should work:

```dart
  HtmlWidget(
    html,
    customStylesBuilder: (element) {
      if (element.localName == 'figure') {
        return { 'margin': '0' };
      }

      return null;
    }
  ),
```

**Comment by HenglyEver** [comment]
Yes. it works. Thanks :D

**Comment by DFelten** [comment]
@daohoangson I tried this within the widget factory via 

```dart
switch (meta.element.localName) {
  case 'figure':
    meta['margin'] = '0';
    break;
}
```

But this isn't working. The margin still keeps the same. With the customStylesBuilder it's working, but I would like to have my styling in one place.

**Comment by daohoangson** [comment]
@DFelten setting the margin there doesn't work because of the execution order, [as noted here](https://github.com/daohoangson/flutter_widget_from_html/tree/master/packages/core#custom-widgetfactory), the order is `WidgetFactory.parse(BuildMetadata)` before `HtmlWidget.customStylesBuilder` so in your particular case:

- Your `parse`
- Then the built-in `parse` via `super.parse()`
- And finally `customStylesBuilder` (if set)

The margin styles will be:

- `margin: 0` from yours
- `margin: 1em 40px` from built-in

The later declaration will cascade over the former one so your zero margin is ignored. If you don't really care about the `FIGURE` tag default styling, just skip calling `super` for it. Something like this:

```dart
switch (meta.element.localName) {
  case 'figure':
   return;
}
```
