### ISSUE TITLE
<code>tag is not working

### ISSUE THREAD

**Issue by sushilbalami** [daohoangson/flutter_widget_from_html#426]
code tag is working for only one line if we have multiple line code tag is not working it shows on 1 line 
i was trying to show C Program on Code Tag.
![image](https://user-images.githubusercontent.com/33893625/106712137-a2b9bc00-6620-11eb-82e2-1f8e0e5cccff.png)

**Comment by daohoangson** [comment]
Can you include a reproducible piece of HTML? Your CODE tag has multiple lines I think?

**Comment by sushilbalami** [comment]
Any C Program...
```
#include <stdio.h>
int main() {
    int n, i, flag = 0;
    printf("Enter a positive integer: ");
    scanf("%d", &n);

    for (i = 2; i <= n / 2; ++i) {

        // condition for non-prime
        if (n % i == 0) {
            flag = 1;
            break;
        }
    }

    if (n == 1) {
        printf("1 is neither prime nor composite.");
    }
    else {
        if (flag == 0)
            printf("%d is a prime number.", n);
        else
            printf("%d is not a prime number.", n);
    }

    return 0;
}
```

**Comment by daohoangson** [comment]
If your HTML looks like this:

```html
Blah

<code>#include <stdio.h>
int main() {
    int n, i, flag = 0;
    printf("Enter a positive integer: ");
    scanf("%d", &n);

    for (i = 2; i <= n / 2; ++i) {

        // condition for non-prime
        if (n % i == 0) {
            flag = 1;
            break;
        }
    }

    if (n == 1) {
        printf("1 is neither prime nor composite.");
    }
    else {
        if (flag == 0)
            printf("%d is a prime number.", n);
        else
            printf("%d is not a prime number.", n);
    }

    return 0;
}</code>
```

|  Google Chrome rendering | This package rendering |
|  --- |  --- |
| <img src="https://user-images.githubusercontent.com/239336/108654327-fe2dea00-74fa-11eb-9f43-d53ec2bbd4b2.png"> | <img src="https://user-images.githubusercontent.com/239336/108654421-37665a00-74fb-11eb-8394-aa78b7a272a8.png" /> |

This is by design. If you want to render multiple line of code, use the PRE tag. Checkout the [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code) for more information.
