### ISSUE TITLE
Check if HTML contains unsupported elements

### ISSUE THREAD

**Issue by bamnet** [daohoangson/flutter_widget_from_html#457]
Is there a way to check if a chunk of HTML can be rendered using this library or if it contains unknown / unsupported elements?

In my application, I would prefer to use the native elements exposed by `HtmlWidget` whenever possible (this library is awesome!), but if the HTML blob I need to render contains unsupported tags, like `<script>`, `<custom-element>`, etc I'd like to be able to know beforehand and pop out to a full `WebView` instead.

Is there any way to achieve even a rough version of this?

**Comment by daohoangson** [comment]
It's possible to check if a tag is recognized by the package (that information is not expose right now though) but doing so is a bit backward in the "ideology" of HTML rendering. Basically this package (and browsers in fact) will happily render everything you throw at it. If a tag has special meaning (e.g. it is a table) it will be rendered that way, otherwise the textual contents are shown. That's how HTML specs can include new tags and it works fine with older browser, something like this is perfectly valid HTML:

```html
  <video controls width="320" height="176">
    <source src="https://www.w3schools.com/html/mov_bbb.mp4" type="video/mp4">
    <source src="https://www.w3schools.com/html/mov_bbb.ogg" type="video/ogg">
    Your browser does not support HTML5 video.
  </video>
```

For your use case, it may be easier to run some regex looking for SCRIPT tag before switching to `WebView`. For better performance, you can render the entire HTML within `HtmlWidget` and only renders the script-y part in web view, e.g. all those social media oEmbed things.

**Comment by bamnet** [comment]
Thanks for the fast response!  I'll start with a whitelisted elements approach scraped from your supported/tags.html page.

**Comment by daohoangson** [comment]
Note: that page lists SCRIPT tag as it actually has special meaning (e.g. script contents are ignored) 😆
