### ISSUE TITLE
Any way to increase the height of the youtube video frame?

### ISSUE THREAD

**Issue by ShantanuBalse** [daohoangson/flutter_widget_from_html#48]
The Youtube video progress bar gets hidden under the bottom edge of the frame if I play one of the videos that Youtube recommends. I know this is probably because the width and height of the frame is set inside the <iframe> tag but it would have been great if we could manually change it. Is that possible?

**Comment by daohoangson** [comment]
The WebView resize itself so nothing should be cut off. Can you share the html causing issue? A screenshot would be helpful too.

**Comment by ShantanuBalse** [comment]
The iframe tag looks like this:

`<iframe width=\"560\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/JSTdArrLaCo\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen><\/iframe>`

And here's a screenshot:
![screen](https://i.ibb.co/0DTTBSP/Capture.png)
Notice the bottom edge where the progress bar gets hidden.

This only happens after I play one of the videos from the recommended videos that Youtube shows _after_ the original has finished playing.

**Comment by daohoangson** [comment]
> This only happens after I play one of the videos from the recommended videos that Youtube shows after the original has finished playing.

Oh, that's weird. Let me try this on my device.

**Comment by daohoangson** [comment]
Well, I found the problem.

After the video is done, if you click the link to view another video, YouTube will open the full version instead of the embed version (notice the top bar with YouTube and search icon). In your iframe code, the width and height are specified so the WebView stays at that aspect ratio. If you remove the width and height from the iframe code, the WebView will resize itself to show the whole page...

Probably I will capture user click and open browser instead of opening new url within the WebView. Do you think that's a good workaround?

**Comment by ShantanuBalse** [comment]
> Probably I will capture user click and open browser instead of opening new url within the WebView. Do you think that's a good workaround?

Either that or if possible, the video should open in a different fullscreen view like so:
![screen](https://i.ibb.co/FgdcNGf/Screenshot-20190607-133133.png)

**Comment by daohoangson** [comment]
v0.2.2 has been released, this version will open WebView link in external browser. This should solve the issue being discussed here.
