### ISSUE TITLE
Exception when there are negative margins

### ISSUE THREAD

**Issue by LuisCampos97** [daohoangson/flutter_widget_from_html#507]
Before thank you very much for the package, it is really very good.

I supposedly found a bug, which I am not sure is a bug which is the following: when a negative margin is passed in the styles, the html is not rendered and gives an exception.

My code is this:
```dart
HtmlWidget("""
                    <h1>TITLE</h1>
                    <div style="background-color: blue;margin: 50px -2px">
                      This is my DIV element.
                    </div>
                    """,
                        enableCaching: true,
                        textStyle: TextStyle(color: Color(0XFF9E9E9E), fontSize: 14),
                        hyperlinkColor: Colors.blue,
                        onTapUrl: (String url) => Helpers.launchURL(url))
```

And gives the following exception:

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter_widget_from_html_core/src/data/css.dart': Failed assertion: line 158 pos 15: 'number >= 0': is not true.
The relevant error-causing widget was HtmlWidget...

In my project I receive HTML via the api so I can't edit it directly, and I have to use it even with negative margins

Can someone please explain to me how to solve please?
Thank you very much.

**Comment by daohoangson** [comment]
The core package has a new release (version `0.6.1+1`) which includes the fix for this. You should able to run `flutter pub upgrade` within your app to get it.

The fix is a temporary workaround to avoid exception with negative margin. I have opened a new issue to add support for negative margin/padding (they are perfectly valid in CSS world), please follow #509 if you need those.

**Comment by LuisCampos97** [comment]
Thank you very much @daohoangson
