### ISSUE TITLE
Change TD widget

### ISSUE THREAD

**Issue by CripyIce** [daohoangson/flutter_widget_from_html#508]
Hi there,
I see that when I'm having an HTML code with `table` it becomes a `Row` widget with equally sized children inside.
I would like to make the first `td`/`Row` child a flexible width child.
Is there a way to return a widget that have a parsed HTML child using this library? For example:
```dart
Container(
  child: parseHTML(element.children.first).
)
```

Thanks!

**Comment by daohoangson** [comment]
How did you discover the `Row` widget? This package doesn't use row to render table cells, you are probably using some other package...

Anyway, it's not possible to replace the first row with flexible width cells anyway because the table layout is managed by one single widget (the [HtmlTable](https://github.com/daohoangson/flutter_widget_from_html/blob/master/packages/core/lib/src/widgets/html_table.dart) custom widget). I do plan to support better cell width control though, you can follow #209 for that.

**Comment by CripyIce** [comment]
I guessed the usage of `Row` usage, but if this is not the case so be it.
No way to replace that table logic?
If the only case is to wait for #209 then I'll wait.
Thanks!

**Comment by daohoangson** [comment]
Technically you can use a custom `WidgetFactory` and replace the usage of `HtmlTable` widget with something else. In previous versions of this package, the `flutter_layout_grid` package was used and it does support intrinsic column width. There are problems with that approach though, e.g. you won't be able to nest a table into another. It may work for your use case.

**Comment by daohoangson** [comment]
There are some old tags that uses `flutter_layout_grid` to render tables. It may require significant work to adapt it for current version of this package though.

**Comment by daohoangson** [comment]
I'm closing this issue in favor of #531. Please follow that one if you want to be notified about better column width support in `TABLE`.
