### ISSUE TITLE
BBCode support

### ISSUE THREAD

**Issue by mark8044** [daohoangson/flutter_widget_from_html#550]
Consider adding BBCode support in order to add more range to flutter_widget_from_html.   With BBCode's tag based structure hopefully translation will be similar to what is already in place

**Comment by daohoangson** [comment]
BB code support is unlikely to be included since the bb code renderer often requires additional data to work properly. Some site has bb code that renders a slide show by an internal id (e.g. `[SLIDE]123456[/SLIDE]`). In my experience, using the server side rendered HTML directly in the app is simpler. Take a look at this XenForo app that I built https://github.com/daohoangson/flutter-tinhte_demo

**Comment by mark8044** [comment]
@daohoangson This makes total sense
