### ISSUE TITLE
AppStore issues, NSMicrophoneUsageDescription

### ISSUE THREAD

**Issue by ChrisZi** [daohoangson/flutter_widget_from_html#567]
## Steps to Reproduce

When I update flutter_widget_from_html to version 0.6.2 and upload my app to AppStore I am getting such a message:

Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSMicrophoneUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

But I don't use the microphone and I don't need to use it.

<details>
  <summary>HTML</summary>

```html
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
```
</details>

<details>
  <summary>Tesing environment</summary>

```
```
</details>

## Expected results

No request to use the microphone as it was in previous versions.

## Actual results

I can't deploy app.

**Comment by daohoangson** [comment]
Oh, the `v0.6.2` has just been released and you upgraded already? That's fast.

This may happen because this version has support for `AUDIO` tag (it can play mp3 now). The underlying package makes use of the `AVAudioSession` api which triggers app store scanner. If your app doesn't use the microphone in anyway (no video recording etc.), there are two ways to deal with this, actually three ways:

## Option 1: Switch to `flutter_widget_from_html_core` package

Use a custom `WidgetFactory` and choose which tags you want to support. If you don't plan to render iframe, video tags etc. in your HTML, doing this way will shave a few MB from your app.

<details>

<summary>my_html_widget.dart</summary>

```dart
import 'package:flutter/widgets.dart';
import 'package:flutter_widget_from_html_core/flutter_widget_from_html_core.dart';
import 'package:fwfh_cached_network_image/fwfh_cached_network_image.dart';
import 'package:fwfh_chewie/fwfh_chewie.dart';
import 'package:fwfh_svg/fwfh_svg.dart';
import 'package:fwfh_url_launcher/fwfh_url_launcher.dart';
import 'package:fwfh_webview/fwfh_webview.dart';

class MyHtmlWidget extends StatelessWidget {
  final String html;

  const MyHtmlWidget(this.html, {Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return HtmlWidget(
      html,
      factoryBuilder: () => MyWidgetFactory(),
    );
  }
}

class MyWidgetFactory extends WidgetFactory
    with
        CachedNetworkImageFactory, // for optimized image rendering
        ChewieFactory, // for VIDEO support
        SvgFactory, // for SVG support
        UrlLauncherFactory, // to launch URLs
        WebViewFactory // for IFRAME support
{}
```

</details>

## Option 2: Modify `ios/Podfile` to strip the microphone related code.

Check [the just_audio document](https://pub.dev/packages/just_audio#ios) for details. It looks like below. 

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # ADD THE NEXT SECTION
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'AUDIO_SESSION_MICROPHONE=0'
      ]
    end
    
  end
end
```

## Option 3: Or you can just update `Info.plist` to explain the microphone usage.

**Comment by ChrisZi** [comment]
Thank you for your quick response. In my case option 2 it didn't work, but option 3 it worked well.
Best regards.

**Comment by DFelten** [comment]
Thanks for this info. I think this should be a part of the Readme :)

**Comment by marcellocamara** [comment]
I have the same issue here, now with the latest version, 0.14.11

![Captura de Tela 2024-03-10 às 20 53 15](https://github.com/daohoangson/flutter_widget_from_html/assets/18273071/46604214-dbf3-4a4a-89c2-c2694459c8b9)

**Comment by daohoangson** [comment]
This is mentioned in the README:

> <img width="961" alt="Screenshot 2024-03-11 at 09 26 47" src="https://github.com/daohoangson/flutter_widget_from_html/assets/239336/24570aba-462a-43cd-b69b-6900c8fd7a55">

There are 3 different ways to fix it, as mentioned here https://github.com/daohoangson/flutter_widget_from_html/issues/567#issuecomment-897700650. If you don't use the extra features, switching to core is probably the best option.
