### ISSUE TITLE
List view - allow passing a ScrollController

### ISSUE THREAD

**Issue by frankpepermans** [daohoangson/flutter_widget_from_html#605]
## Use case

Many thanks for all of your wonderful work, awesome package :)

I want to use the `ListView` `Renderer` option, but AFAIK, there is then no way to also restore a scroll position for example,
Of course I could use the `Column` default option and then wrap it inside a `SingleChildScrollWidget` for example, but then lost the performance gain of course.

So would it be possible to maybe allow passing a `ScrollController`?

**Comment by frankpepermans** [comment]
Sure, I'll have a look :)

**Comment by frankpepermans** [comment]
Hey,

I've created a fork that allows passing a ScrollController, but it feels like api clutter really, perhaps it's better to handle this via the WidgetFactory?

There, you can override the handler which returns a ListView.builder, only problem is, that the item builder relies on a private property, the _anchors (on my phone typing this, can't recall the full name).

So maybe we can just allow access to that via a getter?

Then, you can fully override that same handler, and just add a ScrollController that way.

Thoughts?

**Comment by daohoangson** [comment]
Ah I see your point. You don't want to add a new param directly into the `HtmlWidget`? Because it already has too many?

We probably has two ways to do this:

1. Add another param into `HtmlWidget`, then use it when we build the `ListView`. This is not very clean.
2. Change the `RenderMode` enum into some kind of a sealed class and `RenderMode.listView` can be created with an optional controller?

**Comment by frankpepermans** [comment]
Work great, many thanks :)
