### ISSUE TITLE
Leading and trailing whitespace within `<pre>` tag is trimmed

### ISSUE THREAD

**Issue by Mosc** [daohoangson/flutter_widget_from_html#622]
## Steps to Reproduce

<details>
  <summary>HTML</summary>

```html
<pre>
  L          TE
    A       A
      C    V
       R A
       DOU
       LOU
      REUSE
      QUE TU
      PORTES
    ET QUI T'
    ORNE O CI
     VILISÉ
    OTE-  TU VEUX
     LA    BIEN
    SI      RESPI
            RER       - Apollinaire
</pre>
```
</details>

<details>
  <summary>HtmlWidget configuration</summary>

```dart
HtmlWidget(html);  
```
</details>

## Expected results

I would expect leading and trailing whitespace within `<pre>` tags to be rendered, such that in the example the first line starts with two spaces.

## Actual results

The first line in a `<pre>` tag loses any intentional indentation.

**Comment by daohoangson** [comment]
I'm working on this.

**Comment by daohoangson** [comment]
v0.8.2 has been released with the fix for this. Please try upgrading to see whether it works for you. I have tried it with the mentioned HTML and it seems to be fine.

<img width="300" alt="Screen Shot 2021-11-09 at 18 33 58" src="https://user-images.githubusercontent.com/239336/140916911-4772e054-12fc-4f43-86e0-ae91d6d7d552.png">

**Comment by Mosc** [comment]
Thanks, my testing also shows that the issue has been resolved!

**Comment by daohoangson** [comment]
That's great to hear 🎉
