### ISSUE TITLE
Resize to scale?

### ISSUE THREAD

**Issue by wiradikusuma** [daohoangson/flutter_widget_from_html#638]
## Use case

This widget will fit in one line when displayed on my 27" monitor: `HtmlWidget('<font size="200">Some Long Sentence Alright</font>')`.

On the phone, however, it will be wrapped:

```
Some Long 
Sentence Alright
```

**Unless I scale it down.** But I don't want to resize it to an arbitrary dimension (e.g. 200x100) because the content is dynamic. When that widget is resized, I also want to resize other `HtmlWidget` proportionally. This means I can't just wrap the widget inside `FittedBox`.

## Proposal

It would be great if `HtmlWidget` has a `scale` property that will draw it accordingly.

**Comment by daohoangson** [comment]
I'm not sure I understand your request correctly. Are you asking for a `scale` property that will be `1.0` by default, which will draw the HTML contents at full size. If you pass `0.5` for that property, it should draw everything at half the size?

**Comment by wiradikusuma** [comment]
That's correct. Otherwise, (leveraging other widgets) how else can we do that? `Transform.scale` is not ideal. I actually asked that question in Stack Overflow: https://stackoverflow.com/q/70055994

**Comment by daohoangson** [comment]
I have read through the StackOverflow link, I have a question: you want FittedBox behavior but couldn't use it because you don't know the actual dimensions. If you don't know the dimensions, how can you calculate the `scale` property for `HtmlWidget`?

**Comment by wiradikusuma** [comment]
Sorry I think my question in SO is confusing. I have the `scale`, so what I want is actually `Transform.scale`. Unfortunately, it has some big issues (mentioned in SO). In summary, I want `FittedBox` behaviour using scale (that I already have the value).

**Comment by daohoangson** [comment]
I have some demo with `Text` here https://dartpad.dev/4ee9753a5bbda2162f40fb8a7079b033. As you already know, this issue is not directly tied to `HtmlWidget`.

<img width="1545" alt="Screen Shot 2021-11-26 at 23 29 13" src="https://user-images.githubusercontent.com/239336/143609736-fa035a71-897a-4c0c-890b-fe21ba0c8601.png">

- `Transform.scale` only performs transform during painting so it layouts in full size, that's why the text is wrapped.
- The text won't wrap inside `UnconstrainedBox` but the box complains when text width is too big (because layouting is in full size).
- That's why I had to implement a custom render box, basically a simpler version of `UnconstrainedBox`.

**Comment by wiradikusuma** [comment]
Thanks for taking the time to show me. There's still "phantom margin" (screencast attached), making it not ideal for my use case, because the _position_ of my widget is set using left/right (absolute positioning). Do you mind posting your answer in the SO post? There's a 100-point bounty :)

https://user-images.githubusercontent.com/481995/143613638-84931708-244c-4695-af55-4097f8270c0e.mp4

**Comment by daohoangson** [comment]
I have revised my implementation a bit and [commented on SO](https://stackoverflow.com/a/70129655/308114), let's continue over there.

I'm closing this as it is no longer an issue with this package in particular.
