### ISSUE TITLE
Unable to apply inline margin to image element

### ISSUE THREAD

**Issue by glen-84** [daohoangson/flutter_widget_from_html#763]
## Steps to Reproduce

<details>
  <summary>HTML</summary>

```html
      <p>Para 1</p>
      <p>
        Para 2
        <a href="#" target="_blank">
          <img
            src="https://github.githubassets.com/favicons/favicon.svg"
            width="24"
            height="24"
            style="margin-inline-end: 10px; vertical-align: middle;"
            title="Text" /><strong>text</strong></a> more text
      </p>
      <p>Para 3</p>
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
// default from try.fwfh.dev
```
</details>

<details>
  <summary>Tesing environment</summary>

```
(not applicable)
```
</details>

## Expected results

A right margin on the image element.

## Actual results

No margin.

![image](https://user-images.githubusercontent.com/261509/166144050-c2f90964-75cb-4b12-9acb-30f16b40b5d8.png)

**Comment by daohoangson** [comment]
Looks like a conflict between `margin` and `vertical-align`. Let me take a closer look.

**Comment by daohoangson** [comment]
This bug is not easy to fix but I have good news: the next major version (probably a 0.9) has already fixed this as seen below:

![Simulator Screen Shot - iPhone 13 Pro Max - 2022-05-01 at 23 18 54](https://user-images.githubusercontent.com/239336/166154862-e238b7d1-7783-43cb-ba97-8829e128ed40.png)

That version has been worked on for quite a long time (see #649 #748) to address short comings of the old renderer in edge cases like this.

**Comment by glen-84** [comment]
Any idea when that might be released?

**Comment by daohoangson** [comment]
`v0.11.0-alpha.1` has been released with the fix for this. Please try upgrading and see whether it works for you.
