### ISSUE TITLE
How to use Scrollable.ensureVisible with this package to scroll to a specified element and make sure it is visible in the viewport?

### ISSUE THREAD

**Issue by giorgio79** [daohoangson/flutter_widget_from_html#783]
I would like to be able to scroll to html elements that are out of view (when a user taps on a button outside of the html widget) eg

- https://api.flutter.dev/flutter/widgets/Scrollable/ensureVisible.html
- https://diamantidis.github.io/2021/10/10/exploring-flutter-scrollable-ensurevisible
- https://stackoverflow.com/questions/49153087/flutter-scrolling-to-a-widget-in-listview

**Comment by mark8044** [comment]
I accomplished this, however I did it by having multiple HtmlWidget inside a listview, and give each HtmlWidget a GlobalKey, then I could scroll to the specific one I wanted.

If you are using a single HtmlWidget, I would guess you could accomplish this internally with some kind of jquery scrollTo type of function

**Comment by giorgio79** [comment]
Can you give an example? I guess that would defeat that purpose as we can just use multiple native RichText elements?

Here is what I have in mind:
https://pub.dev/packages/anchor_scroll_controller
jump to anchors from outsite the htmlwidget...

**Comment by mark8044** [comment]
> Can you give an example code? I guess that would defeat that purpose as we can just use multiple native RichText elements?
> 
> Here is what I have in mind: https://pub.dev/packages/anchor_scroll_controller jump to anchors from outsite the htmlwidget...

My implementation is massive and complex, so its hard to tear it out for example code, but think something like this

```
Column
  - HTMLWidget
  - HTMLWidget
  - HTMLWidget
  - HTMLWidget(key:_myGlobalKey)
  - HTMLWidget
```

Then to scroll to it, just do 
```
              Scrollable.ensureVisible(
                  _myGlobalKey.currentContext!,
                  alignment: 0,
                  duration: Duration(milliseconds: 500)
              );
```

You could easily do the same thing with https://pub.dev/packages/anchor_scroll_controller as you mentioned.

I don't think it defeats the purpose.  HTMLWIdget can render some very complex HTML, but if your content is just text that be rendered with RichText, then yes that's a good idea since it would be more lightweight.  

The point here is that HTMLWidget can render MUCH more then a RichText widget can do and does so very easily (just feed it HTML), so there is probably a reason you are using HTMLWidget over RichText.

Regardless, doing the scroll is a breeze using a global key.  Alternatively as mentioned, doing an internal JS scroll is probably possible, I just haven't tried to do it myself.  But on another platform (Appcelerator Titanium) I did things exactly that way, I rendered everything as one giant single HTMLWidget and then used JS to scroll to certain elements.  I would image it would work here as well

**Comment by daohoangson** [comment]
You will need to make sure `HtmlWidget` element is rendered in Flutter element tree, then it should allow you to jump to any anchor within. Internally it uses global keys to keep track of visible widgets and `ensureVisible` to scroll.

This gets tricky in "lazy" list view because the actual list item is not built until the viewport is nearby. Even more so if you are using sliver within a `CustomScrollView`...
